`#CAUSE Analysis 
#SEDENTARY -> LBM
#SEDENTARY -> BMI
#SEDENTARY -> WHR
#SEDENTARY -> WC
#SEDENTARY -> %TBF
#SEDENTARY -> VAT

#MODERATE -> LBM
#MODERATE -> BMI
#MODERATE -> WHR
#MODERATE -> WC
#MODERATE -> %TBF
#MODERATE -> VAT

#MVPA -> LBM
#MVPA -> BMI
#MVPA -> WHR
#MVPA -> WC
#MVPA -> %TBF
#MVPA -> VAT

#VIGOROUS -> LBM
#VIGOROUS -> BMI
#VIGOROUS -> WHR
#VIGOROUS -> WC
#VIGOROUS -> %TBF
#VIGOROUS -> VAT

#SSOE -> LBM
#SSOE -> BMI
#SSOE -> WHR
#SSOE -> WC
#SSOE -> %TBF
#SSOE -> VAT
